# Generated by Django 5.2 on 2025-04-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carpathians", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skilllevel",
            options={"ordering": ("order",)},
        ),
        migrations.AddField(
            model_name="skilllevel",
            name="order",
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
