# Generated by Django 5.2 on 2025-04-26 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carpathians", "0002_alter_skilllevel_options_skilllevel_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="difficulty",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="routes",
                to="carpathians.skilllevel",
            ),
        ),
    ]
